export enum CourseCategory {
  PROGRAMMING = 'PROGRAMMING',
  DESIGN = 'DESIGN',
  BUSINESS = 'BUSINESS',
  MARKETING = 'MARKETING',
  PERSONAL_DEVELOPMENT = 'PERSONAL_DEVELOPMENT',
  MUSIC = 'MUSIC',
  PHOTOGRAPHY = 'PHOTOGRAPHY',
  OTHER = 'OTHER',
}
